service_mapping = {
    'CMED': 'Cardiac Medical',
    'CSURG': 'Cardiac Surgical',
    'DENT': 'Dental',
    'ENT': 'Ear, Nose, Throat',
    'EYE': 'Eye diseases',
    'GU': 'Genitourinary',
    'GYN': 'Gynecological',
    'MED': 'Medical',
    'NB': 'Newborn',
    'NBB': 'Newborn',
    'NMED': 'Neurologic Medical',
    'NSURG': 'Neurologic Surgical',
    'OBS': 'Obstetrics',
    'ORTHO': 'Orthopedic',
    'OMED': 'Orthopedic Medical',
    'PSURG': 'Plastic Surgical',
    'PSYCH': 'Psychiatric',
    'SURG': 'Surgery',
    'TRAUM': 'Trauma',
    'TSURG': 'Thoracic Surgical',
    'VSURG': 'Vascular Surgical'}